### ISSUE TITLE
Get current location automatically

### ISSUE THREAD

**Issue by jayan2019** [leanmotherfuckers/react-native-map-link#59]
I think it would be better if `sourceLatitude` & `sourceLongitude` is not defined, capture the current location automatically. It would be a good feature for this package. Thanks in advance 🙏🏻

**Comment by tschoffelen** [comment]
In most cases, you are not required to specify those, they are optional.

**Comment by jayan2019** [comment]
Thank you for your response @tschoffelen. Yes you are right they are optional, But what I suggest is setting the devices current location for it would be more useful. Then the user can simply click the Directions and found best route. This is my own suggestions for improvement. Please feel free to close this issue if it is not acceptable in this place 😊

**Comment by tschoffelen** [comment]
I see what you mean. The reason we don't do that at the moment is that it would make the library more difficult to use, because:

1. You'd always need to ask permission to use the user's location if you want to use this library.
2. There would be a delay between the user pressing the button and actually opening the directions app, since getting the user's current location is an asynchronous task.

And since most apps that you can open with the maps link already assume you want directions from your current location, I don't think this is something we should add ourselves.

**Comment by jayan2019** [comment]
I agree with you @tschoffelen. Thanks for your valuable comments and you time. I will close this issue.
