### ISSUE TITLE
'comgooglemaps' not being detected on ios with Expo

### ISSUE THREAD

**Issue by monjohn** [leanmotherfuckers/react-native-map-link#69]
First of all I want to say thank you for open-sourcing this library. It is well-done and super useful.

I want to revisit issue #39 since I am encountering the same issue. It successfully detects Waze, but not Google Maps. 

I too am using Expo and my app.json file includes:
```    
"ios": {
    "infoPlist": {
      "LSApplicationQueriesSchemes": [
          "comgooglemaps",
          "apple-maps",
          "citymapper",
          "waze"
        ]
      }
  }
```

Just like in that other issue, I editing `contacts.js` in the following way:

```
export const prefixes = {
...
- 'google-maps': isIOS ? 'comgooglemaps://' : 'https://maps.google.com/',
+ 'google-maps': 'https://maps.google.com/',
...
}
```

When I do this, the Google Maps app is detected and it opens as I would expect. But without this, it never appears on the list. In #39, it says that 'comgooglemaps' is more reliable, but this does not seem to be the case.

Thanks.

**Comment by tschoffelen** [comment]
Thanks @monjohn!

I see that I wasnt really clear in my comment on #39.

The problem with this solution is that opening the app might work well, but detecting it won’t, since a `http://` URL can always be opened (in Safari), so the detection will always indicate that Google Maps is installed with this change, even if it isn’t. That’s why there is a need to use a custom URL scheme for the detection part of the script.

However, you’re indeed not the first person to indicate that the `comgooglemaps://` scheme doesn’t seem to be working in all cases, so we probably need to do some research to see if there is a new one we should use, or whether we should accept that there is no proper way to detect it and just always show it, with the possibility that that might lead to Google Maps being opened in the browser when the user doesn’t have the app installed.

**Comment by monjohn** [comment]
@tschoffelen Thanks for the reply! It is weird, after a bunch of searching, I can't find issues where other people are having this problem on iOS in general. And Google's own page still indicates that this is the correct URL.

**Comment by tschoffelen** [comment]
Just to confirm, you did rebuild/reinstall the app after making the changes to your Expo config file, right? 

https://github.com/leanmotherfuckers/react-native-map-link/blob/master/docs/expo.md#rebuild-your-app

I was doing some testing just now as well, and for me the url scheme `comgooglemap://` still works too.

**Comment by monjohn** [comment]
I did rebuild, but I missed the note at the bottom about it only working in the standalone app. 😊

**Comment by tschoffelen** [comment]
Ah! That explains it all! Expo doesn't have a way to edit the Plist file of their own app dynamically of course, so they can't add URL schemes on demand.

Okay for me to close this one?

**Comment by monjohn** [comment]
Yep. Thanks for the help!
